# Generated by Django 2.2.17 on 2020-11-15 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('slot', models.IntegerField(choices=[(1, '10AM-11AM'), (2, '11AM-12PM'), (3, '12PM-1PM'), (4, '1PM-2PM'), (5, '2PM-3PM'), (6, '3PM-4PM'), (7, '4PM-5PM'), (8, '5PM-6PM')], default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('date', 'slot', 'user')},
            },
        ),
    ]
